version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    restart: always
    # Удалены публикации портов
    networks:
      - internal

  llamaserver:
    image: ghcr.io/ggerganov/llama.cpp:server
    container_name: llamaserver
    restart: always
    # Порты не публикуем наружу
    volumes:
      - ./models:/models
    command: >
      -m /models/llama_1b_q8_0.gguf
      --port 8000
      --host 0.0.0.0
      -n 512
    networks:
      - internal

  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB: echodatabase
    # Удалён маппинг порта
    volumes:
      - ./data/pg_data:/var/lib/postgresql/data
      - ./init_scripts:/docker-entrypoint-initdb.d
    secrets:
      - postgres_password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U dbuser -d echodatabase" ]
      interval: 10s
      retries: 5
      start_period: 5s
    networks:
      - internal

  rasa-nlu:
    image: rasa/rasa:3.6.4
    container_name: rasa-nlu
    restart: always
    volumes:
      - ./rasa:/app
    entrypoint: ""  # <--- отключаем стандартный ENTRYPOINT
    command: >
      bash -c "rasa train && rasa run --enable-api --port 5005"
    networks:
      - internal

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    restart: always
    ports:
      - "3001:3000"  # доступ к метабейзу на localhost:3001
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: echodatabase
      MB_DB_PORT: 5432
      MB_DB_USER: dbuser
      MB_DB_PASS_FILE: /run/secrets/postgres_password
      MB_DB_HOST: postgres
    depends_on:
      - postgres
    secrets:
      - postgres_password
    networks:
      - internal
      - public



  web-server:
    build: ./websrv
    ports:
      - "5000:5000"   # единственный внешний порт
    volumes:
      - ./data:/app/data
      - ./websrv/templates:/app/templates
      - ./websrv/static:/app/static
    restart: always
    environment:
      FLASK_PORT: 5000
      DB_HOST: postgres
      DB_NAME: echodatabase
      DB_USER: dbuser
      DB_PASSWORD_FILE: /run/secrets/postgres_password
    secrets:
      - postgres_password
    depends_on:
      - rabbitmq
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - internal
      - public

  video2sound:
    build: ./vid2snd
    volumes:
      - ./data:/app/data
    restart: always
    depends_on:
      - rabbitmq
      - web-server
    networks:
      - internal

  videofatigue:
    build: ./videofat
    volumes:
      - ./data:/app/data
    restart: always
    depends_on:
      - rabbitmq
      - web-server
    networks:
      - internal

  videoemo:
    build: ./videoemo
    volumes:
      - ./data:/app/data
    restart: always
    depends_on:
      - rabbitmq
      - web-server
    networks:
      - internal

  asr:
    build: ./asr
    restart: always
    volumes:
      - ./models:/app/onnx
      - ./data:/app/data
    environment:
      MODEL_TYPE: ctc
      ONNX_DIR: onnx
    depends_on:
      - rabbitmq
      - web-server
      - video2sound
    networks:
      - internal

  audfeat:
    build: ./audfeat
    restart: always
    volumes:
      - ./data:/app/data
    depends_on:
      - rabbitmq
      - web-server
      - video2sound
    networks:
      - internal

  audioemo:
    build: ./audioemo
    restart: always
    volumes:
      - ./data:/app/data
    depends_on:
      - rabbitmq
      - web-server
      - video2sound
    networks:
      - internal

  audiofat:
    build: ./audiofat
    restart: always
    volumes:
      - ./data:/app/data
    depends_on:
      - rabbitmq
      - web-server
      - video2sound
    networks:
      - internal


  logger:
    build: ./dblogger
    restart: always
    volumes:
      - ./data:/app/data
    environment:
      DB_HOST: postgres
      DB_NAME: echodatabase
      DB_USER: dbuser
      DB_PASSWORD_FILE: /run/secrets/postgres_password
    secrets:
      - postgres_password
    depends_on:
      - rabbitmq
      - web-server
      - video2sound
      - asr
      - audfeat
    networks:
      - internal

  textemo:
    build: ./textemo
    restart: always
    volumes:
      - ./models/emotext:/app/model
    depends_on:
      - rabbitmq
      - web-server
      - video2sound
      - asr
    networks:
      - internal

  main:
    build: ./main
    restart: always
    volumes:
      - ./data:/app/data
    depends_on:
      - rabbitmq
      - web-server
      - video2sound
      - asr
      - llamaserver
    environment:
      LLM_MAX_NEW_TOKEN: 100
      LLM_TEMPERATURE: 0.7
      LLM_ADRESS: "http://llamaserver:8000/v1.7"
      LLM_NAME: "gigachat"
      LLM_API_KEY_FILE: /run/secrets/llm_api_key
    secrets:
      - llm_api_key
    networks:
      - internal
      - public
  tts:
    build: ./tts
    restart: always
    volumes:
      - ./models:/app/models
      - ./data:/app/data
    environment:
      SPEAKER: xenia
      SAMPLE_RATE: 48000
    depends_on:
      - rabbitmq
      - web-server
      - video2sound
      - asr
      - main
    networks:
      - internal

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    # Убран внешний маппинг порта
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data/prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - internal

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"   # единственный внешний порт для Grafana
    volumes:
      - ./data/grafana-storage:/var/lib/grafana
    networks:
      - internal
      - public

  nodeexplorer:
    image: quay.io/prometheus/node-exporter:latest
    container_name: nodeexplorer
    restart: always
    # Убран публикация порта
    command:
      - '--path.rootfs=/host'
    volumes:
      - /:/host:ro
    networks:
      - internal

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: always
    # Убран публикация порта
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - internal

secrets:
  postgres_password:
    file: ./secrets/postgres_password
  llm_api_key:
    file: ./secrets/llm_api_key

networks:
  internal:
    internal: true
  public:
    driver: bridge
