version: '1.0'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    restart: always
    ports:
       - 5672:5672
       - 15672:15672

  llamaserver:
    image: ghcr.io/ggerganov/llama.cpp:server-cuda
    container_name: llamaserver
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./models:/models
    command: >
      -m /models/llama_1b_q8_0.gguf
      --port 8000
      --host 0.0.0.0
      -n 512
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB: echodatabase
    ports:
      - "5430:5432"
    volumes:
      - ./data/pg_data:/var/lib/postgresql/data
      - ./init_scripts:/docker-entrypoint-initdb.d
    secrets:
      - postgres_password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U dbuser -d echodatabase" ]
      interval: 10s
      retries: 5
      start_period: 5s


  web-server:
    build: ./websrv
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    restart: always
    environment:
      FLASK_PORT: 5000
    depends_on:
      - rabbitmq

  video2sound:
    build: ./vid2snd
    volumes:
      - ./data:/app/data
    restart: always
    depends_on:
      - rabbitmq
      - web-server

  asr:
    build: ./asr
    restart: always
    volumes:
      - ./models:/app/onnx
      - ./data:/app/data
    environment:
      MODEL_TYPE: ctc
      ONNX_DIR: onnx
    depends_on:
      - rabbitmq
      - web-server
      - video2sound



  audfeat:
    build: ./audfeat
    restart: always
    volumes:
      - ./data:/app/data
    depends_on:
      - rabbitmq
      - web-server
      - video2sound

  logger:
    build: ./dblogger
    restart: always
    volumes:
      - ./data:/app/data

    environment:
      DB_HOST: postgres
      DB_NAME: echodatabase
      DB_USER: dbuser
      DB_PASSWORD_FILE: /run/secrets/postgres_password
    secrets:
      - postgres_password

    depends_on:
      - rabbitmq
      - web-server
      - video2sound
      - asr
      - audfeat

  main:
    build: ./main
    restart: always
    volumes:
      - ./data:/app/data
    depends_on:
      - rabbitmq
      - web-server
      - video2sound
      - asr
      - llamaserver


  tts:
    build: ./tts
    restart: always
    volumes:
      - ./models:/app/models
      - ./data:/app/data
    environment:
      SPEAKER: xenia
      SAMPLE_RATE: 48000
    depends_on:
      - rabbitmq
      - web-server
      - video2sound
      - asr
      - main



secrets:
  postgres_password:
    file: ./secrets/postgres_password

