FROM python:3.10

WORKDIR /app
RUN mkdir onnx
RUN apt-get update && apt-get install -y \
    libsndfile1  ffmpeg\
    && rm -rf /var/lib/apt/lists/*

ENV MODEL_TYPE = "ctc"
ENV ONNX_DIR = onnx


COPY ./requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install git+https://github.com/salute-developers/GigaAM.git




COPY ./app.py ./

# Запускаем приложение
CMD ["python", "app.py"]
