FROM python:3.10

WORKDIR /app

RUN apt-get update && apt-get install -y \
    libsndfile1 \
    && rm -rf /var/lib/apt/lists/*

COPY ./requirements.txt ./
COPY ./app.py ./
COPY ./model.bin ./

RUN pip install --no-cache-dir -r requirements.txt


CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
